[project]
name = "nonebot-plugin-gpt"
version = "1.1.2"
description = "Nonebot2's plugin of ChatGPT "
authors = [
    {name = "nek0us", email = "nekouss@mail.com"},
]
license = {text = "GPL3"}
dependencies = ["ChatGPTWeb>=0.4.3","nonebot2>=2.0.0","nonebot-plugin-htmlkit","nonebot-plugin-alconna","nonebot_plugin_localstore","Markdown>=3.0","Pillow>=10.0"]
requires-python = ">=3.10"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/nek0us/nonebot-plugin-gpt"
Repository = "https://github.com/nek0us/nonebot-plugin-gpt"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
